### ISSUE TITLE
Just dies with exception on Win10

### ISSUE THREAD

**Issue by dzavalishin** [ianopolous/JPC#9]
G:\games\JPC\JPC-3.0>java -jar JPCApplication.jar -boot fda -fda resources/images/floppy.img
ьрЁ. 05, 2023 3:24:03 PM org.jpc.j2se.JPCApplication main
INFO: Using configuration specified on command line
Exception in thread "main" java.lang.IllegalStateException
        at org.jpc.j2se.JPCApplication.getResources(JPCApplication.java:593)
        at org.jpc.j2se.JPCApplication.<init>(JPCApplication.java:205)
        at org.jpc.j2se.JPCApplication.main(JPCApplication.java:766)

G:\games\JPC\JPC-3.0>java -version
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

**Comment by jdstroy** [comment]
This isn't a Windows 10 problem; the JPC code targets an older version of the Java runtime class library.  Please try JPC with JRE8; you can use [Adoptium Temurin](https://adoptium.net/temurin/releases/?os=windows&arch=any&package=jre&version=8) or any other JRE8 runtime.
